# formatters format, use . to make a new one then name it
# in the handlers
"enabled" = true
[formatters.detailed]
"class" = "logging.Formatter"
#8s right-justifies level name, -8s will left-justify
"format" = "[%(asctime)s] [%(levelname)8s] - %(message)s"
"datefmt" = "%d/%m/%y %H:%M:%S"
# handlers are where logging info goes
[handlers.console]
"class" = "logging.StreamHandler"
"formatter" = "detailed"
[root]
"level" = "INFO"         #Default: INFO, DEBUG for more verbose information
"handlers" = ["console"]
