"""features

Revision ID: 00c04e256a07
Revises: 250e3115f166
Create Date: 2022-04-18 12:02:14.564071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c04e256a07'
down_revision = '250e3115f166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ivn', sa.Float(), nullable=True),
    sa.Column('iqr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stars.id'], name=op.f('fk_features_id_stars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    # ### end Alembic commands ###
