"""adm-ade

Revision ID: 00fb40a87f48
Revises: 3a00a6ddce6c
Create Date: 2022-02-16 11:57:18.799344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fb40a87f48'
down_revision = '3a00a6ddce6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('average differential magnitude', sa.Float(), nullable=True))
    op.add_column('timeseries', sa.Column('average differential error', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseries', 'average differential error')
    op.drop_column('timeseries', 'average differential magnitude')
    # ### end Alembic commands ###
