"""rename

Revision ID: 250e3115f166
Revises: 691d565b2d21
Create Date: 2022-04-07 13:25:35.582768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e3115f166'
down_revision = '691d565b2d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('adm', sa.Float(), nullable=True))
    op.add_column('timeseries', sa.Column('ade', sa.Float(), nullable=True))
    op.drop_column('timeseries', 'average differential error')
    op.drop_column('timeseries', 'average differential magnitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('average differential magnitude', sa.FLOAT(), nullable=True))
    op.add_column('timeseries', sa.Column('average differential error', sa.FLOAT(), nullable=True))
    op.drop_column('timeseries', 'ade')
    op.drop_column('timeseries', 'adm')
    # ### end Alembic commands ###
