"""init

Revision ID: 3a00a6ddce6c
Revises: 
Create Date: 2022-01-27 15:54:44.823544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a00a6ddce6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('magnitude_median', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stars'))
    )
    op.create_table('label',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('idref', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idref'], ['stars.id'], name=op.f('fk_label_idref_stars')),
    sa.PrimaryKeyConstraint('name', 'dataset', name=op.f('pk_label')),
    sa.UniqueConstraint('name', 'dataset', name='_name_dataset_unique')
    )
    op.create_table('timeseries',
    sa.Column('tsid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('idref', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idref'], ['stars.id'], name=op.f('fk_timeseries_idref_stars')),
    sa.PrimaryKeyConstraint('tsid', name=op.f('pk_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('label')
    op.drop_table('stars')
    # ### end Alembic commands ###
