"""init

Revision ID: 52f61463b2df
Revises: 
Create Date: 2022-01-10 10:55:13.889286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f61463b2df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name', 'dataset', name=op.f('pk_stars')),
    sa.UniqueConstraint('name', 'dataset', name='_name_dataset_unique')
    )
    op.create_table('timeseries',
    sa.Column('star_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name=op.f('fk_timeseries_star_id_stars')),
    sa.PrimaryKeyConstraint('star_id', 'time', name=op.f('pk_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('stars')
    # ### end Alembic commands ###
