"""new_init

Revision ID: 691d565b2d21
Revises: 
Create Date: 2022-04-06 16:56:54.159303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691d565b2d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
    sa.UniqueConstraint('dataset', name=op.f('uq_dataset_dataset'))
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('dsid', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('magnitude_median', sa.Float(), nullable=True),
    sa.Column('variable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dsid'], ['dataset.id'], name=op.f('fk_stars_dsid_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stars')),
    sa.UniqueConstraint('name', name=op.f('uq_stars_name'))
    )
    op.create_table('timeseries',
    sa.Column('tsid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('average differential magnitude', sa.Float(), nullable=True),
    sa.Column('average differential error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name=op.f('fk_timeseries_star_id_stars')),
    sa.PrimaryKeyConstraint('tsid', name=op.f('pk_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('stars')
    op.drop_table('dataset')
    # ### end Alembic commands ###
