"""init

Revision ID: a7844e40f8b2
Revises: 
Create Date: 2022-01-06 15:24:22.535043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7844e40f8b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'dataset', name=op.f('pk_star'))
    )
    op.create_table('timeseries',
    sa.Column('star_name', sa.Text(), nullable=False),
    sa.Column('star_dataset', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['star_dataset'], ['star.dataset'], name=op.f('fk_timeseries_star_dataset_star')),
    sa.ForeignKeyConstraint(['star_name'], ['star.name'], name=op.f('fk_timeseries_star_name_star')),
    sa.PrimaryKeyConstraint('star_name', 'star_dataset', 'time', name=op.f('pk_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('star')
    # ### end Alembic commands ###
