"""init

Revision ID: dd26d21e4ab9
Revises: 
Create Date: 2022-05-18 12:52:54.712312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd26d21e4ab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
    sa.UniqueConstraint('dataset', name=op.f('uq_dataset_dataset'))
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('dsid', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('magnitude_median', sa.Float(), nullable=True),
    sa.Column('variable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dsid'], ['dataset.id'], name=op.f('fk_stars_dsid_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stars'))
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ivn', sa.Float(), nullable=True),
    sa.Column('iqr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name=op.f('fk_features_star_id_stars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_table('timeseries',
    sa.Column('tsid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('adm', sa.Float(), nullable=True),
    sa.Column('ade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name=op.f('fk_timeseries_star_id_stars')),
    sa.PrimaryKeyConstraint('tsid', name=op.f('pk_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('features')
    op.drop_table('stars')
    op.drop_table('dataset')
    # ### end Alembic commands ###
